import dash
import dash_core_components as dcc
import dash_html_components as html

# == Main Application ==
app = dash.Dash()
app.title = 'Republic Polytechnic Student Intake'

# == Control Variables ==
colors = {
    'background': '#fff',
    'text': '#000'
}

markers = {
    '0':'circle','1':'square','2':'diamond','3':'cross','4':'x-open','5':'x-dot','6':'triangle-up','7':'triangle-left','8':'pentagon','9':'hexagon','10':'octagon',
    '11':'hourglass','12':'hash-open','13':'bowtie','14':'hash','15':'diamond-cross-open','16':'star-square-dot'
}

acad_years = ['2011/2012', '2012/2013', '2013/2014', '2014/2015', '2015/2016', '2016/2017']

schools = {

    'SAS': {
        '0': {
            'dip_bs': '168',
            'dip_bio': '127',
            'dip_es': '118',
            'dip_msa': None,
            'dip_ms': '92',
            'dip_ps': '291'
        },
        '1': {
            'dip_bs': '147',
            'dip_bio': '118',
            'dip_es': '193',
            'dip_msa': None,
            'dip_ms': '96',
            'dip_ps': '228'
        },
        '2': {
            'dip_bs': '149',
            'dip_bio': '124',
            'dip_es': '110',
            'dip_msa': None,
            'dip_ms': '127',
            'dip_ps': '244'
        },
        '3': {
            'dip_bs': '130',
            'dip_bio': '155',
            'dip_es': '118',
            'dip_msa': '51',
            'dip_ms': '127',
            'dip_ps': '210'
        },
        '4': {
            'dip_bs': '121',
            'dip_bio': '147',
            'dip_es': '108',
            'dip_msa': '42',
            'dip_ms': '122',
            'dip_ps': '187'
        },
        '5': {
            'dip_bs': '112',
            'dip_bio': '156',
            'dip_es': '86',
            'dip_msa': '52',
            'dip_ms': '94',
            'dip_ps': '167'
        }
    },
    'SEG': {
        '0': {
            'dip_ce': '328',
            'dip_aa': '106',
            'dip_ae': '77',
            'dip_am': '88',
            'dip_be': '95',
            'dip_ca': '74',
            'dip_cae': None,
            'dip_dee': '98',
            'dip_eee': None,
            'dip_edb': None,
            'dip_esm': None,
            'dip_gbem': None,
            'dip_iom': '108',
            'dip_mn': '72',
            'dip_ree': '57',
            'dip_scm': '122',
        },
        '1': {
            'dip_ce': '342',
            'dip_aa': '58',
            'dip_ae': '79',
            'dip_am': '88',
            'dip_be': '80',
            'dip_ca': '72',
            'dip_cae': None,
            'dip_dee': '85',
            'dip_eee': None,
            'dip_edb': None,
            'dip_esm': None,
            'dip_gbem': None,
            'dip_iom': '261',
            'dip_mn': '36',
            'dip_ree': '51',
            'dip_scm': '113',
        },
        '2': {
            'dip_ce': '298',
            'dip_aa': '61',
            'dip_ae': '69',
            'dip_am': '88',
            'dip_be': None,
            'dip_ca': '86',
            'dip_cae': None,
            'dip_dee': None,
            'dip_eee': '185',
            'dip_edb': None,
            'dip_esm': None,
            'dip_gbem': None,
            'dip_iom': '119',
            'dip_mn': None,
            'dip_ree': '59',
            'dip_scm': '79',
        },
        '3': {
            'dip_ce': '259',
            'dip_aa': '64',
            'dip_ae': '71',
            'dip_am': '88',
            'dip_be': None,
            'dip_ca': None,
            'dip_cae': None,
            'dip_dee': None,
            'dip_eee': '155',
            'dip_edb': None,
            'dip_esm': None,
            'dip_gbem': None,
            'dip_iom': '99',
            'dip_mn': None,
            'dip_ree': '73',
            'dip_scm': '79',
        },
        '4': {
            'dip_ce': '365',
            'dip_aa': '79',
            'dip_ae': '84',
            'dip_am': '105',
            'dip_be': None,
            'dip_ca': None,
            'dip_cae': None,
            'dip_dee': None,
            'dip_eee': '226',
            'dip_edb': None,
            'dip_esm': '50',
            'dip_gbem': '75',
            'dip_iom': '99',
            'dip_mn': None,
            'dip_ree': None,
            'dip_scm': '87',
        },
        '5': {
            'dip_ce': '257',
            'dip_aa': '62',
            'dip_ae': '70',
            'dip_am': '101',
            'dip_be': None,
            'dip_ca': None,
            'dip_cae': None,
            'dip_dee': None,
            'dip_eee': '169',
            'dip_edb': '49',
            'dip_esm': '66',
            'dip_gbem': '58',
            'dip_iom': '81',
            'dip_mn': None,
            'dip_ree': None,
            'dip_scm': '61',
        }
    },
    'SOH': {
        '0': {
            'dip_cemb': None,
            'dip_crsm': '229',
            'dip_hhm': '176',
            'dip_iem': '186',
            'dip_rco': '58',
            'dip_wlsm': '62'
        },
        '1': {
            'dip_cemb': None,
            'dip_crsm': '228',
            'dip_hhm': '122',
            'dip_iem': '243',
            'dip_rco': '81',
            'dip_wlsm': '96'
        },
        '2': {
            'dip_cemb': None,
            'dip_crsm': '292',
            'dip_hhm': '180',
            'dip_iem': '264',
            'dip_rco': '80',
            'dip_wlsm': '103'
        },
        '3': {
            'dip_cemb': None,
            'dip_crsm': '255',
            'dip_hhm': '159',
            'dip_iem': '220',
            'dip_rco': '98',
            'dip_wlsm': '97'
        },
        '4': {
            'dip_cemb': None,
            'dip_crsm': '202',
            'dip_hhm': '154',
            'dip_iem': '198',
            'dip_rco': '103',
            'dip_wlsm': '78'
        },
        '5': {
            'dip_cemb': '193',
            'dip_crsm': None,
            'dip_hhm': '151',
            'dip_iem': '186',
            'dip_rco': '96',
            'dip_wlsm': '58'
        }
    },
    'SOI': {
        '0': {
            'dip_ba': '338',
            'dip_bis': '331',
            'dip_idm': '128',
            'dip_ism': None,
            'dip_it': '266',
            'dip_itsm': '78',
            'dip_msd': None
        },
        '1': {
            'dip_ba': '291',
            'dip_bis': '373',
            'dip_idm': '122',
            'dip_ism': None,
            'dip_it': '237',
            'dip_itsm': '76',
            'dip_msd': '55'
        },
        '2': {
            'dip_ba': '221',
            'dip_bis': '222',
            'dip_idm': '124',
            'dip_ism': None,
            'dip_it': '250',
            'dip_itsm': '64',
            'dip_msd': '65'
        },
        '3': {
            'dip_ba': '168',
            'dip_bis': '175',
            'dip_idm': '96',
            'dip_ism': None,
            'dip_it': '204',
            'dip_itsm': '83',
            'dip_msd': '64'
        },
        '4': {
            'dip_ba': '173',
            'dip_bis': '181',
            'dip_idm': '105',
            'dip_ism': '83',
            'dip_it': '173',
            'dip_itsm': '69',
            'dip_msd': '67'
        },
        '5': {
            'dip_ba': '130',
            'dip_bis': '165',
            'dip_idm': '80',
            'dip_ism': '81',
            'dip_it': '145',
            'dip_itsm': None,
            'dip_msd': '48'
        }
    },
    'SHL': {
        '0': {
            'dip_ha': '48',
            'dip_hmp': '79',
            'dip_hsm': None,
            'dip_oal': '172',
            'dip_sc': None,
            'dip_ses': '176',
            'dip_slm': '153'
        },
        '1': {
            'dip_ha': '133',
            'dip_hmp': '118',
            'dip_hsm': None,
            'dip_oal': '111',
            'dip_sc': '41',
            'dip_ses': '169',
            'dip_slm': '195'
        },
        '2': {
            'dip_ha': '147',
            'dip_hmp': '91',
            'dip_hsm': None,
            'dip_oal': '133',
            'dip_sc': '44',
            'dip_ses': '120',
            'dip_slm': '157'
        },
        '3': {
            'dip_ha': '141',
            'dip_hmp': '138',
            'dip_hsm': None,
            'dip_oal': '84',
            'dip_sc': '59',
            'dip_ses': '134',
            'dip_slm': '102'
        },
        '4': {
            'dip_ha': None,
            'dip_hmp': '107',
            'dip_hsm': '125',
            'dip_oal': '69',
            'dip_sc': '53',
            'dip_ses': '149',
            'dip_slm': '98'
        },
        '5': {
            'dip_ha': None,
            'dip_hmp': '123',
            'dip_hsm': '138',
            'dip_oal': '74',
            'dip_sc': '54',
            'dip_ses': '124',
            'dip_slm': '95'
        }
    },
    'SMC': {
        '0': {
            'dip_cbr': None,
            'dip_cid': '101',
            'dip_hrmp': None,
            'dip_mc': None,
            'dip_sem': None
        },
        '1': {
            'dip_cbr': '50',
            'dip_cid': '107',
            'dip_hrmp': None,
            'dip_mc': None,
            'dip_sem': None
        },
        '2': {
            'dip_cbr': '58',
            'dip_cid': None,
            'dip_hrmp': None,
            'dip_mc': '146',
            'dip_sem': '37'
        },
        '3': {
            'dip_cbr': '51',
            'dip_cid': None,
            'dip_hrmp': '44',
            'dip_mc': '141',
            'dip_sem': '43'
        },
        '4': {
            'dip_cbr': '48',
            'dip_cid': None,
            'dip_hrmp': '54',
            'dip_mc': '106',
            'dip_sem': '47'
        },
        '5': {
            'dip_cbr': '65',
            'dip_cid': None,
            'dip_hrmp': '74',
            'dip_mc': '107',
            'dip_sem': '37'
        }
    },
    'STA': {
        '0': {
            'dip_atm': None,
            'dip_di': '67',
            'dip_dux': None,
            'dip_gd': '84',
            'dip_mpd': None,
            'dip_nm': '203',
            'dip_sa': '59',
            'dip_tam': '81'
        },
        '1': {
            'dip_atm': None,
            'dip_di': '74',
            'dip_dux': None,
            'dip_gd': '78',
            'dip_mpd': None,
            'dip_nm': '191',
            'dip_sa': '61',
            'dip_tam': '89'
        },
        '2': {
            'dip_atm': None,
            'dip_di': '105',
            'dip_dux': None,
            'dip_gd': '82',
            'dip_mpd': None,
            'dip_nm': '184',
            'dip_sa': '73',
            'dip_tam': '102'
        },
        '3': {
            'dip_atm': '86',
            'dip_di': '100',
            'dip_dux': None,
            'dip_gd': '56',
            'dip_mpd': '158',
            'dip_nm': None,
            'dip_sa': '66',
            'dip_tam': None
        },
        '4': {
            'dip_atm': '97',
            'dip_di': None,
            'dip_dux': '91',
            'dip_gd': '64',
            'dip_mpd': '141',
            'dip_nm': None,
            'dip_sa': '74',
            'dip_tam': None
        },
        '5': {
            'dip_atm': '72',
            'dip_di': None,
            'dip_dux': '71',
            'dip_gd': '45',
            'dip_mpd': '121',
            'dip_nm': None,
            'dip_sa': '75',
            'dip_tam': None
        }
    }

}

# == Application Layout ==
app.layout = html.Div(style={'backgroundColor': colors['background']}, children=[
    # Title
    html.H1(children='Republic Polytechnic Student Intake',
            style={'textAlign': 'center', 'color': colors['text']}
            ),
    # Sub-title
    html.Div(children='Statistics showing the total number of students enrolled per course in RP over the years.', style={
        'textAlign': 'center',
        'color': colors['text']
    }),
    html.Hr(style={'width': '50%', 'opacity': '0.1'}),

    dcc.Graph(id='school_SAS',
              figure ={
              'data': [
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_bs'],
                                             schools['SAS']['1']['dip_bs'],
                                             schools['SAS']['2']['dip_bs'],
                                             schools['SAS']['3']['dip_bs'],
                                             schools['SAS']['4']['dip_bs'],
                                             schools['SAS']['5']['dip_bs']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['0']},
                                            'name':'Biomedical Sciences'},
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_bio'],
                                             schools['SAS']['1']['dip_bio'],
                                             schools['SAS']['2']['dip_bio'],
                                             schools['SAS']['3']['dip_bio'],
                                             schools['SAS']['4']['dip_bio'],
                                             schools['SAS']['5']['dip_bio']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['1']},
                                            'name':'Biotechnology'},
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_es'],
                                             schools['SAS']['1']['dip_es'],
                                             schools['SAS']['2']['dip_es'],
                                             schools['SAS']['3']['dip_es'],
                                             schools['SAS']['4']['dip_es'],
                                             schools['SAS']['5']['dip_es']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['2']},
                                            'name':'Environmental Science'},
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_msa'],
                                             schools['SAS']['1']['dip_msa'],
                                             schools['SAS']['2']['dip_msa'],
                                             schools['SAS']['3']['dip_msa'],
                                             schools['SAS']['4']['dip_msa'],
                                             schools['SAS']['5']['dip_msa']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['3']},
                                            'name':'Marine Science and Aquaculture'},
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_ms'],
                                             schools['SAS']['1']['dip_ms'],
                                             schools['SAS']['2']['dip_ms'],
                                             schools['SAS']['3']['dip_ms'],
                                             schools['SAS']['4']['dip_ms'],
                                             schools['SAS']['5']['dip_ms']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['4']},
                                            'name':'Materials Science'},
                        {'x':acad_years,'y':[schools['SAS']['0']['dip_ps'],
                                             schools['SAS']['1']['dip_ps'],
                                             schools['SAS']['2']['dip_ps'],
                                             schools['SAS']['3']['dip_ps'],
                                             schools['SAS']['4']['dip_ps'],
                                             schools['SAS']['5']['dip_ps']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['5']},
                                            'name':'Pharmaceutical Sciences'},
                      ],
              'layout': {
                        'title': 'School of Applied Science',
                        'plot_bgcolor': colors['background'],
                        'paper_bgcolor': colors['background'],
                        'font': colors['text'],
                        'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                        }
              }),
    html.Hr(style={'width': '70%', 'opacity': '0.1'}),

    dcc.Graph(id='school_SEG',
              figure ={
              'data': [
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_ce'],
                                             schools['SEG']['1']['dip_ce'],
                                             schools['SEG']['2']['dip_ce'],
                                             schools['SEG']['3']['dip_ce'],
                                             schools['SEG']['4']['dip_ce'],
                                             schools['SEG']['5']['dip_ce']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['2']},
                                            'name':'Common Engineering Programme'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_aa'],
                                             schools['SEG']['1']['dip_aa'],
                                             schools['SEG']['2']['dip_aa'],
                                             schools['SEG']['3']['dip_aa'],
                                             schools['SEG']['4']['dip_aa'],
                                             schools['SEG']['5']['dip_aa']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['3']},
                                            'name':'Aerospace Avionics'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_ae'],
                                             schools['SEG']['1']['dip_ae'],
                                             schools['SEG']['2']['dip_ae'],
                                             schools['SEG']['3']['dip_ae'],
                                             schools['SEG']['4']['dip_ae'],
                                             schools['SEG']['5']['dip_ae']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['4']},
                                            'name':'Aerospace Engineering'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_am'],
                                             schools['SEG']['1']['dip_am'],
                                             schools['SEG']['2']['dip_am'],
                                             schools['SEG']['3']['dip_am'],
                                             schools['SEG']['4']['dip_am'],
                                             schools['SEG']['5']['dip_am']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['5']},
                                            'name':'Aviation Management'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_be'],
                                             schools['SEG']['1']['dip_be'],
                                             schools['SEG']['2']['dip_be'],
                                             schools['SEG']['3']['dip_be'],
                                             schools['SEG']['4']['dip_be'],
                                             schools['SEG']['5']['dip_be']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['6']},
                                            'name':'Biomedical Electronics'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_ca'],
                                             schools['SEG']['1']['dip_ca'],
                                             schools['SEG']['2']['dip_ca'],
                                             schools['SEG']['3']['dip_ca'],
                                             schools['SEG']['4']['dip_ca'],
                                             schools['SEG']['5']['dip_ca']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['7']},
                                            'name':'Civil Aviation'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_cae'],
                                             schools['SEG']['1']['dip_cae'],
                                             schools['SEG']['2']['dip_cae'],
                                             schools['SEG']['3']['dip_cae'],
                                             schools['SEG']['4']['dip_cae'],
                                             schools['SEG']['5']['dip_cae']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['8']},
                                            'name':'Communications and Automation Electronics'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_dee'],
                                             schools['SEG']['1']['dip_dee'],
                                             schools['SEG']['2']['dip_dee'],
                                             schools['SEG']['3']['dip_dee'],
                                             schools['SEG']['4']['dip_dee'],
                                             schools['SEG']['5']['dip_dee']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['9']},
                                            'name':'Digital Entertainment Electronics'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_edb'],
                                             schools['SEG']['1']['dip_edb'],
                                             schools['SEG']['2']['dip_edb'],
                                             schools['SEG']['3']['dip_edb'],
                                             schools['SEG']['4']['dip_edb'],
                                             schools['SEG']['5']['dip_edb']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['10']},
                                            'name':'Engineering Design with Business'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_esm'],
                                             schools['SEG']['1']['dip_esm'],
                                             schools['SEG']['2']['dip_esm'],
                                             schools['SEG']['3']['dip_esm'],
                                             schools['SEG']['4']['dip_esm'],
                                             schools['SEG']['5']['dip_esm']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['11']},
                                            'name':'Engineering Systems and Management'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_gbem'],
                                             schools['SEG']['1']['dip_gbem'],
                                             schools['SEG']['2']['dip_gbem'],
                                             schools['SEG']['3']['dip_gbem'],
                                             schools['SEG']['4']['dip_gbem'],
                                             schools['SEG']['5']['dip_gbem']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['12']},
                                            'name':'Green Building Energy Management'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_iom'],
                                             schools['SEG']['1']['dip_iom'],
                                             schools['SEG']['2']['dip_iom'],
                                             schools['SEG']['3']['dip_iom'],
                                             schools['SEG']['4']['dip_iom'],
                                             schools['SEG']['5']['dip_iom']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['13']},
                                            'name':'Industrial and Operations Management'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_mn'],
                                             schools['SEG']['1']['dip_mn'],
                                             schools['SEG']['2']['dip_mn'],
                                             schools['SEG']['3']['dip_mn'],
                                             schools['SEG']['4']['dip_mn'],
                                             schools['SEG']['5']['dip_mn']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['14']},
                                            'name':'Micro and Nanotechnology'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_ree'],
                                             schools['SEG']['1']['dip_ree'],
                                             schools['SEG']['2']['dip_ree'],
                                             schools['SEG']['3']['dip_ree'],
                                             schools['SEG']['4']['dip_ree'],
                                             schools['SEG']['5']['dip_ree']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['15']},
                                            'name':'Renewable Energy Engineering'},
                        {'x':acad_years,'y':[schools['SEG']['0']['dip_scm'],
                                             schools['SEG']['1']['dip_scm'],
                                             schools['SEG']['2']['dip_scm'],
                                             schools['SEG']['3']['dip_scm'],
                                             schools['SEG']['4']['dip_scm'],
                                             schools['SEG']['5']['dip_scm']
                                            ],
                                            'type':'line',
                                            'hoverlabel': {'namelength':-1},
                                            'marker': {'symbol': markers['16']},
                                            'name':'Supply Chain Management'}],
              'layout': {
                        'title': 'School of Engineering',
                        'plot_bgcolor': colors['background'],
                        'paper_bgcolor': colors['background'],
                        'font': colors['text'],
                        'height':700,
                        'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                        }
              }),
        html.Hr(style={'width': '70%', 'opacity': '0.1'}),

        dcc.Graph(id='school_SOH',
                  figure ={
                  'data': [
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_cemb'],
                                                 schools['SOH']['1']['dip_cemb'],
                                                 schools['SOH']['2']['dip_cemb'],
                                                 schools['SOH']['3']['dip_cemb'],
                                                 schools['SOH']['4']['dip_cemb'],
                                                 schools['SOH']['5']['dip_cemb']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['0']},
                                                'name':'Custom Experience Management with Business'},
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_crsm'],
                                                 schools['SOH']['1']['dip_crsm'],
                                                 schools['SOH']['2']['dip_crsm'],
                                                 schools['SOH']['3']['dip_crsm'],
                                                 schools['SOH']['4']['dip_crsm'],
                                                 schools['SOH']['5']['dip_crsm']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['1']},
                                                'name':'Customer Relationship and Service Management'},
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_hhm'],
                                                 schools['SOH']['1']['dip_hhm'],
                                                 schools['SOH']['2']['dip_hhm'],
                                                 schools['SOH']['3']['dip_hhm'],
                                                 schools['SOH']['4']['dip_hhm'],
                                                 schools['SOH']['5']['dip_hhm']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['2']},
                                                'name':'Hotel and Hospitality Management'},
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_iem'],
                                                 schools['SOH']['1']['dip_iem'],
                                                 schools['SOH']['2']['dip_iem'],
                                                 schools['SOH']['3']['dip_iem'],
                                                 schools['SOH']['4']['dip_iem'],
                                                 schools['SOH']['5']['dip_iem']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['3']},
                                                'name':'Integrated Events Management'},
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_rco'],
                                                 schools['SOH']['1']['dip_rco'],
                                                 schools['SOH']['2']['dip_rco'],
                                                 schools['SOH']['3']['dip_rco'],
                                                 schools['SOH']['4']['dip_rco'],
                                                 schools['SOH']['5']['dip_rco']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['4']},
                                                'name':'Restaurant and Culinary Operations'},
                            {'x':acad_years,'y':[schools['SOH']['0']['dip_wlsm'],
                                                 schools['SOH']['0']['dip_wlsm'],
                                                 schools['SOH']['0']['dip_wlsm'],
                                                 schools['SOH']['0']['dip_wlsm'],
                                                 schools['SOH']['0']['dip_wlsm'],
                                                 schools['SOH']['0']['dip_wlsm']
                                                ],
                                                'type':'line',
                                                'hoverlabel': {'namelength':-1},
                                                'marker': {'symbol': markers['5']},
                                                'name':'Wellness, Lifestyle and Spa Management'},
                          ],
                  'layout': {
                            'title': 'School of Hospitality',
                            'plot_bgcolor': colors['background'],
                            'paper_bgcolor': colors['background'],
                            'font': colors['text'],
                            'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                            }
                  }),
            html.Hr(style={'width': '70%', 'opacity': '0.1'}),

            dcc.Graph(id='school_SOI',
                      figure ={
                      'data': [
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_ba'],
                                                     schools['SOI']['1']['dip_ba'],
                                                     schools['SOI']['2']['dip_ba'],
                                                     schools['SOI']['3']['dip_ba'],
                                                     schools['SOI']['4']['dip_ba'],
                                                     schools['SOI']['5']['dip_ba']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['0']},
                                                    'name':'Business Applications'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_bis'],
                                                     schools['SOI']['1']['dip_bis'],
                                                     schools['SOI']['2']['dip_bis'],
                                                     schools['SOI']['3']['dip_bis'],
                                                     schools['SOI']['4']['dip_bis'],
                                                     schools['SOI']['5']['dip_bis']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['1']},
                                                    'name':'Business Information Systems'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_idm'],
                                                     schools['SOI']['1']['dip_idm'],
                                                     schools['SOI']['2']['dip_idm'],
                                                     schools['SOI']['3']['dip_idm'],
                                                     schools['SOI']['4']['dip_idm'],
                                                     schools['SOI']['5']['dip_idm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['2']},
                                                    'name':'Interactive and Digital Media'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_ism'],
                                                     schools['SOI']['1']['dip_ism'],
                                                     schools['SOI']['2']['dip_ism'],
                                                     schools['SOI']['3']['dip_ism'],
                                                     schools['SOI']['4']['dip_ism'],
                                                     schools['SOI']['5']['dip_ism']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['3']},
                                                    'name':'Infocomm Security Management'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_it'],
                                                     schools['SOI']['1']['dip_it'],
                                                     schools['SOI']['2']['dip_it'],
                                                     schools['SOI']['3']['dip_it'],
                                                     schools['SOI']['4']['dip_it'],
                                                     schools['SOI']['5']['dip_it']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['4']},
                                                    'name':'Information Technology'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_itsm'],
                                                     schools['SOI']['1']['dip_itsm'],
                                                     schools['SOI']['2']['dip_itsm'],
                                                     schools['SOI']['3']['dip_itsm'],
                                                     schools['SOI']['4']['dip_itsm'],
                                                     schools['SOI']['5']['dip_itsm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['5']},
                                                    'name':'IT Service Management'},
                                {'x':acad_years,'y':[schools['SOI']['0']['dip_msd'],
                                                     schools['SOI']['1']['dip_msd'],
                                                     schools['SOI']['2']['dip_msd'],
                                                     schools['SOI']['3']['dip_msd'],
                                                     schools['SOI']['4']['dip_msd'],
                                                     schools['SOI']['5']['dip_msd']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['6']},
                                                    'name':'Mobile Software Development'},
                              ],
                      'layout': {
                                'title': 'School of Infocomm',
                                'plot_bgcolor': colors['background'],
                                'paper_bgcolor': colors['background'],
                                'font': colors['text'],
                                'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                                }
                      }),
            html.Hr(style={'width': '70%', 'opacity': '0.1'}),

            dcc.Graph(id='school_SHL',
                      figure ={
                      'data': [
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_ha'],
                                                     schools['SHL']['1']['dip_ha'],
                                                     schools['SHL']['2']['dip_ha'],
                                                     schools['SHL']['3']['dip_ha'],
                                                     schools['SHL']['4']['dip_ha'],
                                                     schools['SHL']['5']['dip_ha']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['0']},
                                                    'name':'Healthcare Administration'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_hmp'],
                                                     schools['SHL']['1']['dip_hmp'],
                                                     schools['SHL']['2']['dip_hmp'],
                                                     schools['SHL']['3']['dip_hmp'],
                                                     schools['SHL']['4']['dip_hmp'],
                                                     schools['SHL']['5']['dip_hmp']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['1']},
                                                    'name':'Health Management and Promotion'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_hsm'],
                                                     schools['SHL']['1']['dip_hsm'],
                                                     schools['SHL']['2']['dip_hsm'],
                                                     schools['SHL']['3']['dip_hsm'],
                                                     schools['SHL']['4']['dip_hsm'],
                                                     schools['SHL']['5']['dip_hsm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['2']},
                                                    'name':'Health Services Management'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_oal'],
                                                     schools['SHL']['1']['dip_oal'],
                                                     schools['SHL']['2']['dip_oal'],
                                                     schools['SHL']['3']['dip_oal'],
                                                     schools['SHL']['4']['dip_oal'],
                                                     schools['SHL']['5']['dip_oal']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['3']},
                                                    'name':'Outdoor and Adventure Learning'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_sc'],
                                                     schools['SHL']['1']['dip_sc'],
                                                     schools['SHL']['2']['dip_sc'],
                                                     schools['SHL']['3']['dip_sc'],
                                                     schools['SHL']['4']['dip_sc'],
                                                     schools['SHL']['5']['dip_sc']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['4']},
                                                    'name':'Sports Coaching'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_ses'],
                                                     schools['SHL']['1']['dip_ses'],
                                                     schools['SHL']['2']['dip_ses'],
                                                     schools['SHL']['3']['dip_ses'],
                                                     schools['SHL']['4']['dip_ses'],
                                                     schools['SHL']['5']['dip_ses']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['5']},
                                                    'name':'Sports and Exercise Sciences'},
                                {'x':acad_years,'y':[schools['SHL']['0']['dip_slm'],
                                                     schools['SHL']['0']['dip_slm'],
                                                     schools['SHL']['0']['dip_slm'],
                                                     schools['SHL']['0']['dip_slm'],
                                                     schools['SHL']['0']['dip_slm'],
                                                     schools['SHL']['0']['dip_slm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['6']},
                                                    'name':'Sports and Leisure Management'},
                              ],
                      'layout': {
                                'title': 'School of Sports, Health and Leisure',
                                'plot_bgcolor': colors['background'],
                                'paper_bgcolor': colors['background'],
                                'font': colors['text'],
                                'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                                }
                      }),
            html.Hr(style={'width': '70%', 'opacity': '0.1'}),

            dcc.Graph(id='school_SMC',
                      figure ={
                      'data': [
                                {'x':acad_years,'y':[schools['SMC']['0']['dip_cbr'],
                                                     schools['SMC']['1']['dip_cbr'],
                                                     schools['SMC']['2']['dip_cbr'],
                                                     schools['SMC']['3']['dip_cbr'],
                                                     schools['SMC']['4']['dip_cbr'],
                                                     schools['SMC']['5']['dip_cbr']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['0']},
                                                    'name':'Consumer Behaviour and Research'},
                                {'x':acad_years,'y':[schools['SMC']['0']['dip_cid'],
                                                     schools['SMC']['1']['dip_cid'],
                                                     schools['SMC']['2']['dip_cid'],
                                                     schools['SMC']['3']['dip_cid'],
                                                     schools['SMC']['4']['dip_cid'],
                                                     schools['SMC']['5']['dip_cid']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['1']},
                                                    'name':'Communication and Information Design'},
                                {'x':acad_years,'y':[schools['SMC']['0']['dip_hrmp'],
                                                     schools['SMC']['1']['dip_hrmp'],
                                                     schools['SMC']['2']['dip_hrmp'],
                                                     schools['SMC']['3']['dip_hrmp'],
                                                     schools['SMC']['4']['dip_hrmp'],
                                                     schools['SMC']['5']['dip_hrmp']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['2']},
                                                    'name':'Human Resource Management with Psychology'},
                                {'x':acad_years,'y':[schools['SMC']['0']['dip_mc'],
                                                     schools['SMC']['1']['dip_mc'],
                                                     schools['SMC']['2']['dip_mc'],
                                                     schools['SMC']['3']['dip_mc'],
                                                     schools['SMC']['4']['dip_mc'],
                                                     schools['SMC']['5']['dip_mc']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['3']},
                                                    'name':'Mass Communication'},
                                {'x':acad_years,'y':[schools['SMC']['0']['dip_sem'],
                                                     schools['SMC']['1']['dip_sem'],
                                                     schools['SMC']['2']['dip_sem'],
                                                     schools['SMC']['3']['dip_sem'],
                                                     schools['SMC']['4']['dip_sem'],
                                                     schools['SMC']['5']['dip_sem']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['4']},
                                                    'name':'Social Enterprise Management'},
                              ],
                      'layout': {
                                'title': 'School of Management and Communication',
                                'plot_bgcolor': colors['background'],
                                'paper_bgcolor': colors['background'],
                                'font': colors['text'],
                                'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                                }
                      }),
            html.Hr(style={'width': '70%', 'opacity': '0.1'}),

            dcc.Graph(id='school_STA',
                      figure ={
                      'data': [
                                {'x':acad_years,'y':[schools['STA']['0']['dip_atm'],
                                                     schools['STA']['0']['dip_atm'],
                                                     schools['STA']['0']['dip_atm'],
                                                     schools['STA']['0']['dip_atm'],
                                                     schools['STA']['0']['dip_atm'],
                                                     schools['STA']['0']['dip_atm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['0']},
                                                    'name':'Arts and Theatre Management'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_di'],
                                                     schools['STA']['1']['dip_di'],
                                                     schools['STA']['2']['dip_di'],
                                                     schools['STA']['3']['dip_di'],
                                                     schools['STA']['4']['dip_di'],
                                                     schools['STA']['5']['dip_di']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['1']},
                                                    'name':'Design for Interactivity'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_dux'],
                                                     schools['STA']['1']['dip_dux'],
                                                     schools['STA']['2']['dip_dux'],
                                                     schools['STA']['3']['dip_dux'],
                                                     schools['STA']['4']['dip_dux'],
                                                     schools['STA']['5']['dip_dux']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['2']},
                                                    'name':'Design for User Experience'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_gd'],
                                                     schools['STA']['1']['dip_gd'],
                                                     schools['STA']['2']['dip_gd'],
                                                     schools['STA']['3']['dip_gd'],
                                                     schools['STA']['4']['dip_gd'],
                                                     schools['STA']['5']['dip_gd']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['3']},
                                                    'name':'Game Design'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_mpd'],
                                                     schools['STA']['1']['dip_mpd'],
                                                     schools['STA']['2']['dip_mpd'],
                                                     schools['STA']['3']['dip_mpd'],
                                                     schools['STA']['4']['dip_mpd'],
                                                     schools['STA']['5']['dip_mpd']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['4']},
                                                    'name':'Media Production and Design'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_nm'],
                                                     schools['STA']['1']['dip_nm'],
                                                     schools['STA']['2']['dip_nm'],
                                                     schools['STA']['3']['dip_nm'],
                                                     schools['STA']['4']['dip_nm'],
                                                     schools['STA']['5']['dip_nm']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['5']},
                                                    'name':'New Media'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_sa'],
                                                     schools['STA']['1']['dip_sa'],
                                                     schools['STA']['2']['dip_sa'],
                                                     schools['STA']['3']['dip_sa'],
                                                     schools['STA']['4']['dip_sa'],
                                                     schools['STA']['5']['dip_sa']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['6']},
                                                    'name':'Sonic Arts'},
                                {'x':acad_years,'y':[schools['STA']['0']['dip_tam'],
                                                     schools['STA']['1']['dip_tam'],
                                                     schools['STA']['2']['dip_tam'],
                                                     schools['STA']['3']['dip_tam'],
                                                     schools['STA']['4']['dip_tam'],
                                                     schools['STA']['5']['dip_tam']
                                                    ],
                                                    'type':'line',
                                                    'hoverlabel': {'namelength':-1},
                                                    'marker': {'symbol': markers['7']},
                                                    'name':'Technology and Arts Management'},
                              ],
                      'layout': {
                                'title': 'School of Technology for the Arts',
                                'plot_bgcolor': colors['background'],
                                'paper_bgcolor': colors['background'],
                                'font': colors['text'],
                                'legend': dict(x=0,y=1,traceorder='normal',font=dict(family='sans-serif',size=12,color='#000'),bgcolor='rgba(128,128,128,0.1)',bordercolor='#FFFFFF',borderwidth=2)
                                }
                      }),
            html.Hr(style={'width': '70%', 'opacity': '0.1'}),

        html.Div(children='Source: https://www.rp.edu.sg/', style={
            'textAlign': 'right',
            'color': colors['text']
        }),

    ])

if __name__ == '__main__':
    app.run_server(debug=True)
